backend:
  name: git-gateway
  branch: main  # Your default branch

media_folder: "images"  # Folder for uploaded images
public_folder: "/images"

collections:
  - name: "services"
    label: "Services"
    folder: "_data/services"  # Where content is stored
    create: true  # Allow new entries
    fields:
      - { name: "title", label: "Service Name", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
