backend:
  name: github
  branch: main
  repo: farhanprintpress/farhanprintpress # Format: <your-github-username>/<repo>

media_folder: "images"
public_folder: "/images"

collections:
  - name: "services"
    label: "Services"
    folder: "_data/services"
    create: true
    fields:
      - { name: "title", label: "Service Name", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
